export const SET_MEMBERGUID = 'SET_MEMBERGUID'

export const SET_VSHOPGUID = 'SET_VSHOPGUID'

export const SET_VSHOPGUID2 = 'SET_VSHOPGUID2'

export const SET_VSHOPPRODUCTGUID = 'SET_VSHOPPRODUCTGUID'

export const SET_VGROUNPPRODUCTTYPE = 'SET_VGROUNPPRODUCTTYPE'

export const SET_VSHOPDETAIL = 'SET_VSHOPDETAIL'

export const SET_VPRODUCTDETAIL = 'SET_VPRODUCTDETAIL'

export const SET_VORDERGUID = 'SET_VORDERGUID'

export const SET_VITEMADDRESS = 'SET_VITEMADDRESS'
